### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Pachacoti** [rahil-makadia/grss#60]
After updating `grss` I encountered the following issue when handling asteroids such as (3200) Phaethon:
```
>>> fit_sim.filter_lsq()
Iteration		Unweighted RMS		Weighted RMS 		Chi-squared		Reduced Chi-squared
Segmentation fault (core dumped)
```
Python would exit directly. Seems like this has something do with handling the number of parameters to be fitted more than 6?

**Comment by rahil-makadia** [comment]
Hi @Pachacoti, what version of GRSS are you using? If I install from source on the main branch or use the latest version on PyPI, I am not able to replicate the segfault...

P.S. apologies on the delayed response, I just got back from a vacation

**Comment by Pachacoti** [comment]
Just the latest version on GitHub. I did a git pull, got rid of the old version via pip uninstall, and reinstalled it via pip install. Then the issue started to emerge.

**Comment by rahil-makadia** [comment]
Hmm let me try another machine. I suspect there might be some file path definition that works on my laptop but is not universal

**Comment by rahil-makadia** [comment]
I am not able to replicate this on my mac or linux machines with either numeric or analytic partials... Maybe try just removing the GRSS directory in your python environment's site-packages directory and then just re-clone GRSS and check if the issue still persists? I would also just recommend switching to using PyPI instead of github for installing as well if you are able to

**Comment by rahil-makadia** [comment]
Glad to hear it got fixed! And yep that is even more surprising since the upload to PyPI is a github CI action so there is meant to be no difference. For now I'll mark this as closed.

I'm working on some big upgrades to the OD on the `dev` branch so if this issue persists after those as well, feel free to reopen it...
