### ISSUE TITLE
FitSimulation key error

### ISSUE THREAD

**Issue by Pachacoti** [rahil-makadia/grss#68]
`FitSimulation` runs into the following key error with asteroid 530871:
```
>>> fit_sim = fit.FitSimulation(init_sol, obs_df, init_cov, n_iter_max=n_iter_max, de_kernel=de_kernel, radius=body_radius, nongrav_info=nongrav_info)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Software/anaconda3/lib/python3.9/site-packages/grss/fit/fit_simulation.py", line 540, in __init__
    self._parse_observation_arrays(obs_df)
  File "/Software/anaconda3/lib/python3.9/site-packages/grss/fit/fit_simulation.py", line 720, in _parse_observation_arrays
    self.observer_info = get_observer_info(self.obs)
  File "/Software/anaconda3/lib/python3.9/site-packages/grss/fit/fit_utils.py", line 254, in get_observer_info
    c = conv_to_m[sys]
KeyError: None
```
This is the first asteroid that crashes `FitSimulation` I'm aware of. 

On a different yet kind of related note, `get_sbdb_info` appears to me that it doesn't like objects such as long-period comets and interstellar objects. For example, I'll have the following error with `Oumuamua:
```
>>> body_id = '1I'
>>> init_sol, init_cov, nongrav_info = fit.get_sbdb_info(body_id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mthui/Software/anaconda3/lib/python3.9/site-packages/grss/fit/fit_utils.py", line 404, in get_sbdb_info
    elements = get_sbdb_elems(tdes, cov_elems=True)
  File "/home/mthui/Software/anaconda3/lib/python3.9/site-packages/grss/fit/fit_utils.py", line 366, in get_sbdb_elems
    val.append(float(ele['value']))
TypeError: float() argument must be a string or a number, not 'NoneType'
```
The same error for `body_id = 'C/2023 A3'`. However, it does accept `body_id = 'C/1995 O1'`, which is weird.

**Comment by rahil-makadia** [comment]
For 530871, the dataframe is accepting a deprecated discovery measurement because it is missing the corresponding flag in the MPC data. This could be taken care of in the next few days. For now, I would manually drop that observation before feeding `obs_df` to the `FitSimulation` constructor

As far as querying elements with `get_sbdb_info` goes, I have a fix in my commit stack, but it won't get pushed for a while since I am waiting to test some stuff that I have already committed. I will say, that even after I push the fixes, it is likely that hyperbolic (and even some near parabolic) objects might break some of my routines since I haven't really tested for these orbits (I am definitely thinking of the orbital element partial derivative calculations when I say this)

I'll keep the issue open until I actually push the changes

**Comment by rahil-makadia** [comment]
The fix for the bad observations is already in-place for `(530871)` on the MPC's end. Are you getting the same error with other bodies?

**Comment by Pachacoti** [comment]
Yup, I can't remember all of the cases I encountered, because I didn't keep a record of them. But anyway here's one case with 2010 JG87 that causes exactly the same error messages.

**Comment by rahil-makadia** [comment]
I think 2010 JG87 should be fixed now. Can you keep updating this issue with more asteroids that have the same error please?

**Comment by Pachacoti** [comment]
Sure, I'll keep you posted as long as I find more cases like this. It depends on the number of cases I'll be testing though.

**Comment by rahil-makadia** [comment]
The key error should be fixed now. Please create a separate issue if you find more asteroids with the observation error like 2010 JG87
